### ISSUE TITLE
[FEAT] KeywordListView 구현

### ISSUE THREAD

**Issue by sgh002400** [TeamMyDaily/MyDaily_Android#5]

**Comment by 4z7l** [comment]
@sgh002400 
내가 KeywordListActivity만 수정해놨는데 수정하면서 알려주고 싶은 것들 정리함(세미 코드리뷰)


<br>

## 1. strings.xml
- 서버에서 오는 데이터는 리소스에 저장하지 않아도됨
- string에 저장해야 하는건 항상 고정되어있는 "안내문구"
- 데이터는 리소스(xml)에 저장하는 거 아님
- 만약 Recyclerview를 위해 임시 데이터가 필요하다면, 이 부분은 하드코딩 가능 (chip과 관련된 얘기는 아님)
- break line을 넣고 싶다? -> `\n` 사용

<br>

## 2. activity_keyword_list.xml
- 툴바의 오른쪽에 아이콘 설정하고 싶다 -> `app:menu` 사용 (menu_my_page.xml 참고),
- 툴바의 왼쪽에 아이콘 설정하고 싶다 -> `app:navigationIcon` 사용 (activity_goal_detail.xml, activity_daily_detail.xml 참고)

<br>

- layout의 depth를 줄일 수 있도록 생각해보기 : 현재는 constraintlayout이 너무 남발되어있음(이거 내가 수정함)
<br>

- TextView의 width와 height는 웬만하면 ` wrap_content`로
- 굵은 글씨는 `android:textStyle="bold"`
<br>

- Button은 `AppCompatButton`으로 해야 스타일이 잘 적용되는듯 (나도 지금 처음 앎)
<br>

- 앞서 말했듯 데이터는 xml에서 처리하는게 아님. 무조건 **programmatically**하게 처리해야함(우리는 디자이너가 아님, 우리는 개발자임!! 코딩을 해야함)
- 따라서 기존의 고민이었던 chip 여러개 생성은 **chipgroup 하나만 넣고 데이터를 코틀린 파일에서 넣어주는 방법**을 통해 하는거였음! (https://jroomstudio.tistory.com/28)





<br>

> 내가 참고한 사이트
https://jroomstudio.tistory.com/28
https://stackoverflow.com/questions/53557863/change-chip-widget-style-programmatically-not-working-android
https://medium.com/wasd/material-design-chip-%EC%82%AC%EC%9A%A9%EB%B2%95-in-android-154f29f88241

**Comment by 4z7l** [comment]
5b5aded

- 키워드 추가 버튼 구현

<img src="https://user-images.githubusercontent.com/45537782/103735030-85e59500-5030-11eb-97cf-ab137c9ae7dc.gif" width="300px"/>
